### ISSUE TITLE
Calendar doesn't show up when Debug=False

### ISSUE THREAD

**Issue by JoSell95** [monim67/django-bootstrap-datepicker-plus#19]
Hello,

thank you for this great work. Everything works fine for me, when I have Debug=True in my settings.py.
But when I change it to False the calender does not show up.

Thanks in advance.

**Comment by monim67** [comment]
Thanks for your information. This error has been reported many time before, this time you exactly pointed at the cause of it for the first time. I was having really hard time figuring out why it works for some and doesn't for some environments.

The problem is relating to the static files included in this package which are not served automatically by Django in production mode. You need to collect all static files to a single directory to serve them. [Here](https://django-bootstrap-datepicker-plus.readthedocs.io/en/latest/Troubleshooting.html#fix-404-not-found-errors) is the fix.

**Comment by monim67** [comment]
From version 5.0.0 the asset files are served from jsdelivr CDN by default. So no need to worry about serving static files when DEBUG=False.
