### ISSUE TITLE
Highlight certain dates

### ISSUE THREAD

**Issue by xuanzhan12** [monim67/django-bootstrap-datepicker-plus#2]
Is there support for "beforeShowDay" or another method to highlight certain dates?

**Comment by monim67** [comment]
The [beforeShowDay](https://api.jqueryui.com/datepicker/#option-beforeShowDay) is a jQuery-UI-Datepicker event which is not available here because this widget uses [bootstrap-datetimepicker](https://github.com/Eonasdan/bootstrap-datetimepicker).

If you are looking for disabling certain dates you might want to use [disabledDates](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#disableddates) option.

**Comment by xuanzhan12** [comment]
Alright thank you.
